/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.mml.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.mml.MmlPackage;
import org.xtext.example.mydsl.mml.SGD;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SGD</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SGDImpl extends MLAlgorithmImpl implements SGD
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SGDImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MmlPackage.Literals.SGD;
  }

} //SGDImpl
