/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.mml;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SGD</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.mml.MmlPackage#getSGD()
 * @model
 * @generated
 */
public interface SGD extends MLAlgorithm
{
} // SGD
